global.TBL_USERS = "users"
global.TBL_LOGIN_ROLES = "login_roles"
global.TBL_RESTAURANTS = "restaurants"
global.TBL_RESTAURANT_USERS = "restaurant_users"
global.TBL_CATEGORIES = "categories"
global.TBL_RESTAURANT_CATEGORIES = "restaurant_categories"
global.TBL_RESTAURANT_PRODUCTS = "restaurant_products"
global.TBL_PRODUCT_IMAGES = "product_images"
global.TBL_USER_CART = "user_cart"
global.TBL_ORDER_TRANSACTIONS = "order_transactions"
global.TBL_SUB_TRANSACTIONS = "sub_transactions"
global.TBL_NOTIFICATIONS = "notifications"
global.TBL_DEVICE_TOKEN = "device_token"

global.TIMEZONE = "Asia/Kolkata"

